### ISSUE TITLE
Support for requestAttributes

### ISSUE THREAD

**Issue by flqw** [akihyro/spring-boot-ext-logback-access#12]
I just ran into the issue that the access logs do not consider the attributes set by the RemoteIpValve that can be activated by setting ``server.use-forward-headers=true`` in the spring boot application.properties. After a quick search i discovered that this is because the custom ``LogbackAccessValve`` does not implement the requestAttributes functionality. Has this not be done for a specific reason? I would consider doing the work myself if there is nothing special preventing the implementation.

**Comment by flqw** [comment]
I got a first draft working.

see https://github.com/flqw/spring-boot-ext-logback-access/commit/2c7dae0aad95cdfde885622e092752f685298ccf

Just not sure how to handle the setting of ``enableRequestAttributes``. Maybe a custom property via ``@ConfigurationProperties``?

**Comment by akihyro** [comment]
Thanks for report.

I don't have a reason for not implement the requestAttributes.
I'll check it out, and try support!

**Comment by flqw** [comment]
If we can agree on how to set the enableRequesAttributes i'll finish the implementation and make a pull request.

**Comment by flqw** [comment]
Whoops nevermind i didn't see the LogbackAccessConfigurator class. Added the config there https://github.com/flqw/spring-boot-ext-logback-access/commit/5210dd68235c0404029f141d9a94f91aa7ea765f

**Comment by akihyro** [comment]
Thanks for contributing!

Can you change the defaullt to value of "server.use-forward-headers"?
I feel good to automatically enabled.

Can you change the property name to "logback.access.tomcat.enableRequestAttributes"?
I feel good to add "tomcat" prefix, because this property affect to Tomcat only.

**Comment by flqw** [comment]
Done and done. Also added a test.

**Comment by akihyro** [comment]
I merged PR #14, and released v1.4!

http://search.maven.org/#artifactdetails%7Cnet.rakugakibox.springbootext%7Cspring-boot-ext-logback-access%7C1.4%7C

**Comment by flqw** [comment]
:+1:
