### ISSUE TITLE
Response length not available at the time of logging (Tomcat)

### ISSUE THREAD

**Issue by adammichalik** [akihyro/spring-boot-ext-logback-access#4]
spring-boot-ext-logback-access 1.1, Spring Boot 1.3.3, Tomcat embedded 8.0.32

I'm never able to get the response length in the valve - it's always returned as `-1` from the underlying Tomcat response, resulting in a dash `-` being printed in the access log.

However, when I use the generic Spring Boot access log valve configuration (`server.tomcat.accesslog.enabled=true` in `application.properties`), I'm getting the proper response size.

I compared that Spring Boot uses `TomcatEmbeddedServletContainerFactory#addContextValves` to add the valve in `ServerProperties.Tomcat#customizeAccessLog` and spring-boot-ext-logback-access does that with `TomcatEmbeddedServletContainerFactory#addContextCustomizers`. I tried patching spring-boot-ext-logback-access by applying the logic of Spring Boot - using `addContextValves` instead of using a `TomcatContextCustomizer`, but the result was the same - no response size logged.

Using one or the other - `addContextValves` vs. `addContextCustomizers` does affect the order of the valves - valves are processed first and context customizers later (see `TomcatEmbeddedServletContainerFactory#configureContext`), but as I said it did not matter in the end.

Am I missing something or is this indeed an issue in spring-boot-ext-logback-access?

**Comment by fiunchinho** [comment]
Maybe we could create a test that reproduces this error. Could you do it @akihyro ?

**Comment by akihyro** [comment]
@adammichalik @fiunchinho Thanks for report.

I tried to make a test case.
When you release the following comment, an error will occur.

* https://github.com/akihyro/spring-boot-ext-logback-access/blob/f98fb3512142464180a54671902374b11bc253c9/src/test/java/net/rakugakibox/springbootext/logback/access/AbstractJsonAccessEventTest.java#L110
* https://github.com/akihyro/spring-boot-ext-logback-access/blob/f98fb3512142464180a54671902374b11bc253c9/src/test/java/net/rakugakibox/springbootext/logback/access/AbstractJsonAccessEventTest.java#L153

Maybe, when there is not HTTP response header "Content-Length",
the response length will not be logged (= -1).
Do you fit in this case? If this case, I'm going to try support!

##### [FYI] I was compared:

###### In the case of Logback-access:

* https://github.com/qos-ch/logback/blob/v_1.1.7/logback-access/src/main/java/ch/qos/logback/access/tomcat/LogbackValve.java#L258
* https://github.com/qos-ch/logback/blob/v_1.1.7/logback-access/src/main/java/ch/qos/logback/access/tomcat/TomcatServerAdapter.java#L39-L42

###### In the case of Spring Boot (`server.tomcat.accesslog.enabled=true`):

* https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L832-L837
* https://github.com/apache/tomcat/blob/TOMCAT_8_0_0/java/org/apache/catalina/valves/AbstractAccessLogValve.java#L1129-L1151

**Comment by akihyro** [comment]
Fixed the issue: #5.

and, v1.2 has been released!
Please check the work with the v1.2.

http://search.maven.org/#artifactdetails%7Cnet.rakugakibox.springbootext%7Cspring-boot-ext-logback-access%7C1.2%7C

**Comment by adammichalik** [comment]
Thanks a lot for looking into it! I'm currently away from my computer for
the next week, so I'll check the details as soon as I can.
21 kwi 2016 18:27 "Akihiro Kondo" <notifications@github.com> napisał(a):

**Comment by adammichalik** [comment]
Thanks, I tried it out and it works fine. Unfortunately, I found a new regression issue #8 which prevents me from upgrading.

**Comment by akihyro** [comment]
Thanks a lot. The issue #8 was fixed! (PR: #10)

**Comment by adammichalik** [comment]
Works fine in 1.3, thanks!

**Comment by akihyro** [comment]
Thanks a lot for checking!
