### ISSUE TITLE
Regression 1.2: thread name not logged

### ISSUE THREAD

**Issue by adammichalik** [akihyro/spring-boot-ext-logback-access#8]
Due to the refactoring between versions 1.1 and 1.2, the thread name is not logged any more. That was handled by the Logback's default `LogbackValve` from which the `ReconfigurableLogbackValve` inherited in 1.1.

```
ch.qos.logback.access.tomcat.LogbackValve#invoke:

...
addThreadName(accessEvent);
...
```

In 1.2 the implementation was changed to utilise a new own implementation of `LogbackAccessValve`, but the thread name is not set anywhere.

**Comment by akihyro** [comment]
Thanks for report!

Fixed this issue. (PR: #10)
and, v1.3 was released!

http://search.maven.org/#artifactdetails%7Cnet.rakugakibox.springbootext%7Cspring-boot-ext-logback-access%7C1.3%7C

**Comment by adammichalik** [comment]
Works fine in 1.3, thanks!

**Comment by akihyro** [comment]
Thanks a lot for checking!
